### PR TITLE
fix: hardcoded values on backends adjust artifact-publish-repo documentation

### PR DESCRIPTION
**Pull request by caetano-colin**
There are some hardcoded state buckets in some backend.tf files around the repository. These modifications replace it to **UPDATE_APP_INFRA_BUCKET**, which is the value expected by `sed` commands on README.

On `5-app-infra/1-artifact-publish/modules/publish_artifacts/main.tf` using `var.name` to asign a permission causes an error as the API expects the repository_id / name.

On `5-app-infra/2-artifact-publish-repo/README.md`

Added the command `git commit -m "Initialize Repository" --allow-empty` before adding files, so the trigger that is watching this repository has commit history to run the `git diff` command.

### CODE REVIEW

**Comment by renato-rudnicki** [comment]
We also need to remove the hardcoded in the `5-app-infra/6-machine-learning/modules/base_env/main.tf`

See: https://github.com/GoogleCloudPlatform/terraform-google-enterprise-genai/blob/1bfba13950a3f1a7a112058a4a4eafae8c2a0425/5-app-infra/6-machine-learning/modules/base_env/main.tf#L23

Same for lines 48, 70, 86 and 113

**Comment by mariammartins** [comment]
We also need to remove the hardcoded in the `3-networks-dual-svpc/envs/development/main.tf`

```
[3-networks-dual-svpc/envs/development/main.tf](https://github.com/GoogleCloudPlatform/terraform-google-enterprise-genai/blob/main/3-networks-dual-svpc/envs/development/main.tf#63)
```

**Comment by mariammartins** [comment]
We also need to remove the hardcoded in the 5-app-infra/6-machine-learning/modules/base_env/main.tf `3-networks-dual-svpc/envs/development/main.tf`

[3-networks-dual-svpc/envs/development/main.tf](https://github.com/GoogleCloudPlatform/terraform-google-enterprise-genai/blob/main/3-networks-dual-svpc/envs/development/main.tf#L63)

**Comment by mariammartins** [comment]
We also need to remove the hardcoded in the  [3-networks-dual-svpc/envs/development/main.tf](https://github.com/GoogleCloudPlatform/terraform-google-enterprise-genai/blob/main/3-networks-dual-svpc/envs/development/main.tf#L63)

**Comment by caetano-colin** [comment]
Going to implement this changes today, thank you guys

**Pull request merged**
